/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_icu4jni_text_NativeBreakIterator */

#ifndef _Included_com_ibm_icu4jni_text_NativeBreakIterator
#define _Included_com_ibm_icu4jni_text_NativeBreakIterator
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_icu4jni_text_NativeBreakIterator_BI_CHAR_INSTANCE
#define com_ibm_icu4jni_text_NativeBreakIterator_BI_CHAR_INSTANCE 1L
#undef com_ibm_icu4jni_text_NativeBreakIterator_BI_WORD_INSTANCE
#define com_ibm_icu4jni_text_NativeBreakIterator_BI_WORD_INSTANCE 2L
#undef com_ibm_icu4jni_text_NativeBreakIterator_BI_LINE_INSTANCE
#define com_ibm_icu4jni_text_NativeBreakIterator_BI_LINE_INSTANCE 3L
#undef com_ibm_icu4jni_text_NativeBreakIterator_BI_SENT_INSTANCE
#define com_ibm_icu4jni_text_NativeBreakIterator_BI_SENT_INSTANCE 4L
/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    getCharacterInstanceImpl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_getCharacterInstanceImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    getWordInstanceImpl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_getWordInstanceImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    getLineInstanceImpl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_getLineInstanceImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    getSentenceInstanceImpl
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_getSentenceInstanceImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    closeBreakIteratorImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_closeBreakIteratorImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    setTextImpl
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_setTextImpl
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    cloneImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_cloneImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    precedingImpl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_precedingImpl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    isBoundaryImpl
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_isBoundaryImpl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    nextImpl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_nextImpl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    previousImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_previousImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    currentImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_currentImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    firstImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_firstImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    followingImpl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_followingImpl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeBreakIterator
 * Method:    lastImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeBreakIterator_lastImpl
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
