/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_icu4jni_text_NativeDecimalFormat */

#ifndef _Included_com_ibm_icu4jni_text_NativeDecimalFormat
#define _Included_com_ibm_icu4jni_text_NativeDecimalFormat
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DECIMAL_SEPARATOR_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DECIMAL_SEPARATOR_SYMBOL 0L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_SEPARATOR_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_SEPARATOR_SYMBOL 1L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PATTERN_SEPARATOR_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PATTERN_SEPARATOR_SYMBOL 2L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PERCENT_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PERCENT_SYMBOL 3L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ZERO_DIGIT_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ZERO_DIGIT_SYMBOL 4L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DIGIT_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DIGIT_SYMBOL 5L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MINUS_SIGN_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MINUS_SIGN_SYMBOL 6L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PLUS_SIGN_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PLUS_SIGN_SYMBOL 7L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_CURRENCY_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_CURRENCY_SYMBOL 8L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INTL_CURRENCY_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INTL_CURRENCY_SYMBOL 9L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MONETARY_SEPARATOR_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MONETARY_SEPARATOR_SYMBOL 10L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_EXPONENTIAL_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_EXPONENTIAL_SYMBOL 11L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PERMILL_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PERMILL_SYMBOL 12L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PAD_ESCAPE_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PAD_ESCAPE_SYMBOL 13L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INFINITY_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INFINITY_SYMBOL 14L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NAN_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NAN_SYMBOL 15L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SIGNIFICANT_DIGIT_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SIGNIFICANT_DIGIT_SYMBOL 16L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MONETARY_GROUPING_SEPARATOR_SYMBOL
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MONETARY_GROUPING_SEPARATOR_SYMBOL 17L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FORMAT_SYMBOL_COUNT
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FORMAT_SYMBOL_COUNT 18L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PARSE_INT_ONLY
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PARSE_INT_ONLY 0L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_USED
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_USED 1L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DECIMAL_ALWAYS_SHOWN
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DECIMAL_ALWAYS_SHOWN 2L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_INTEGER_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_INTEGER_DIGITS 3L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_INTEGER_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_INTEGER_DIGITS 4L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INTEGER_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_INTEGER_DIGITS 5L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_FRACTION_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_FRACTION_DIGITS 6L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_FRACTION_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_FRACTION_DIGITS 7L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FRACTION_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FRACTION_DIGITS 8L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MULTIPLIER
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MULTIPLIER 9L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_SIZE
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_GROUPING_SIZE 10L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ROUNDING_MODE
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ROUNDING_MODE 11L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ROUNDING_INCREMENT
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_ROUNDING_INCREMENT 12L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FORMAT_WIDTH
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_FORMAT_WIDTH 13L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PADDING_POSITION
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PADDING_POSITION 14L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SECONDARY_GROUPING_SIZE
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SECONDARY_GROUPING_SIZE 15L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SIGNIFICANT_DIGITS_USED
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_SIGNIFICANT_DIGITS_USED 16L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_SIGNIFICANT_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MIN_SIGNIFICANT_DIGITS 17L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_SIGNIFICANT_DIGITS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_MAX_SIGNIFICANT_DIGITS 18L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_LENIENT_PARSE
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_LENIENT_PARSE 19L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_POSITIVE_PREFIX
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_POSITIVE_PREFIX 0L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_POSITIVE_SUFFIX
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_POSITIVE_SUFFIX 1L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NEGATIVE_PREFIX
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NEGATIVE_PREFIX 2L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NEGATIVE_SUFFIX
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_NEGATIVE_SUFFIX 3L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PADDING_CHARACTER
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PADDING_CHARACTER 4L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_CURRENCY_CODE
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_CURRENCY_CODE 5L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DEFAULT_RULESET
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_DEFAULT_RULESET 6L
#undef com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PUBLIC_RULESETS
#define com_ibm_icu4jni_text_NativeDecimalFormat_UNUM_PUBLIC_RULESETS 7L
/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    applyPatternImpl
 * Signature: (IZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_applyPatternImpl
  (JNIEnv *, jclass, jint, jboolean, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    cloneImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_cloneImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    formatLong
 * Signature: (IJLcom/ibm/icu4jni/text/NativeDecimalFormat/FieldPositionIterator;)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_formatLong
  (JNIEnv *, jclass, jint, jlong, jobject);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    formatDouble
 * Signature: (IDLcom/ibm/icu4jni/text/NativeDecimalFormat/FieldPositionIterator;)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_formatDouble
  (JNIEnv *, jclass, jint, jdouble, jobject);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    formatDigitList
 * Signature: (ILjava/lang/String;Lcom/ibm/icu4jni/text/NativeDecimalFormat/FieldPositionIterator;)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_formatDigitList
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    getAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_getAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    getTextAttribute
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_getTextAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;CCLjava/lang/String;CLjava/lang/String;Ljava/lang/String;CCLjava/lang/String;CCCC)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_open
  (JNIEnv *, jclass, jstring, jstring, jchar, jchar, jstring, jchar, jstring, jstring, jchar, jchar, jstring, jchar, jchar, jchar, jchar);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    parse
 * Signature: (ILjava/lang/String;Ljava/text/ParsePosition;Z)Ljava/lang/Number;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_parse
  (JNIEnv *, jclass, jint, jstring, jobject, jboolean);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    setDecimalFormatSymbols
 * Signature: (ILjava/lang/String;CCLjava/lang/String;CLjava/lang/String;Ljava/lang/String;CCLjava/lang/String;CCCC)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_setDecimalFormatSymbols
  (JNIEnv *, jclass, jint, jstring, jchar, jchar, jstring, jchar, jstring, jstring, jchar, jchar, jstring, jchar, jchar, jchar, jchar);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    setSymbol
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_setSymbol
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    setAttribute
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_setAttribute
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    setRoundingMode
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_setRoundingMode
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    setTextAttribute
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_setTextAttribute
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeDecimalFormat
 * Method:    toPatternImpl
 * Signature: (IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_icu4jni_text_NativeDecimalFormat_toPatternImpl
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
