/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_icu4jni_text_NativeCollation */

#ifndef _Included_com_ibm_icu4jni_text_NativeCollation
#define _Included_com_ibm_icu4jni_text_NativeCollation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    openCollator
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_openCollator
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    openCollatorFromRules
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_openCollatorFromRules
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    closeCollator
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_closeCollator
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    compare
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_compare
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getNormalization
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getNormalization
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    setNormalization
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_setNormalization
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getRules
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getRules
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getSortKey
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getSortKey
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    setAttribute
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_setAttribute
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    safeClone
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_safeClone
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getCollationElementIterator
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getCollationElementIterator
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    closeElements
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_closeElements
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_reset
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    next
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_next
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    previous
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_previous
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getMaxExpansion
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getMaxExpansion
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    setText
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_setText
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    getOffset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_icu4jni_text_NativeCollation_getOffset
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_icu4jni_text_NativeCollation
 * Method:    setOffset
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ibm_icu4jni_text_NativeCollation_setOffset
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
