/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_CRC32 */

#ifndef _Included_java_util_zip_CRC32
#define _Included_java_util_zip_CRC32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_zip_CRC32
 * Method:    updateImpl
 * Signature: ([BIIJ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_CRC32_updateImpl
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     java_util_zip_CRC32
 * Method:    updateByteImpl
 * Signature: (BJ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_CRC32_updateByteImpl
  (JNIEnv *, jobject, jbyte, jlong);

#ifdef __cplusplus
}
#endif
#endif
