/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectInputStream */

#ifndef _Included_java_io_ObjectInputStream
#define _Included_java_io_ObjectInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_ObjectInputStream
 * Method:    newInstance
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectInputStream_newInstance
  (JNIEnv *, jclass, jclass, jclass);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldByte
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;B)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldByte
  (JNIEnv *, jclass, jobject, jclass, jstring, jbyte);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldChar
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldChar
  (JNIEnv *, jclass, jobject, jclass, jstring, jchar);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldDouble
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldDouble
  (JNIEnv *, jclass, jobject, jclass, jstring, jdouble);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldFloat
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldFloat
  (JNIEnv *, jclass, jobject, jclass, jstring, jfloat);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldInt
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldInt
  (JNIEnv *, jclass, jobject, jclass, jstring, jint);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldLong
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldLong
  (JNIEnv *, jclass, jobject, jclass, jstring, jlong);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldObject
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldObject
  (JNIEnv *, jclass, jobject, jclass, jstring, jstring, jobject);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldShort
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldShort
  (JNIEnv *, jclass, jobject, jclass, jstring, jshort);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    setFieldBool
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_setFieldBool
  (JNIEnv *, jclass, jobject, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
