/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_Console */

#ifndef _Included_java_io_Console
#define _Included_java_io_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_Console
 * Method:    isatty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_Console_isatty
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_io_Console
 * Method:    setEchoImpl
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_java_io_Console_setEchoImpl
  (JNIEnv *, jclass, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
