/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_Inflater */

#ifndef _Included_java_util_zip_Inflater
#define _Included_java_util_zip_Inflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_zip_Inflater
 * Method:    createStream
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_createStream
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     java_util_zip_Inflater
 * Method:    endImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_endImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    getAdlerImpl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_Inflater_getAdlerImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    getTotalInImpl
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_getTotalInImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    getTotalOutImpl
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_getTotalOutImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    inflateImpl
 * Signature: ([BIIJ)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_Inflater_inflateImpl
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    resetImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_resetImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    setDictionaryImpl
 * Signature: ([BIIJ)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_setDictionaryImpl
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    setInputImpl
 * Signature: ([BIIJ)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_setInputImpl
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    setFileInputImpl
 * Signature: (Ljava/io/FileDescriptor;JIJ)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_Inflater_setFileInputImpl
  (JNIEnv *, jobject, jobject, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
