/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_charset_Charsets */

#ifndef _Included_java_nio_charset_Charsets
#define _Included_java_nio_charset_Charsets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_nio_charset_Charsets
 * Method:    toAsciiBytes
 * Signature: ([CII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_nio_charset_Charsets_toAsciiBytes
  (JNIEnv *, jclass, jcharArray, jint, jint);

/*
 * Class:     java_nio_charset_Charsets
 * Method:    toIsoLatin1Bytes
 * Signature: ([CII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_nio_charset_Charsets_toIsoLatin1Bytes
  (JNIEnv *, jclass, jcharArray, jint, jint);

/*
 * Class:     java_nio_charset_Charsets
 * Method:    toUtf8Bytes
 * Signature: ([CII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_nio_charset_Charsets_toUtf8Bytes
  (JNIEnv *, jclass, jcharArray, jint, jint);

/*
 * Class:     java_nio_charset_Charsets
 * Method:    asciiBytesToChars
 * Signature: ([BII[C)V
 */
JNIEXPORT void JNICALL Java_java_nio_charset_Charsets_asciiBytesToChars
  (JNIEnv *, jclass, jbyteArray, jint, jint, jcharArray);

/*
 * Class:     java_nio_charset_Charsets
 * Method:    isoLatin1BytesToChars
 * Signature: ([BII[C)V
 */
JNIEXPORT void JNICALL Java_java_nio_charset_Charsets_isoLatin1BytesToChars
  (JNIEnv *, jclass, jbyteArray, jint, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
