/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_RealToString */

#ifndef _Included_java_lang_RealToString
#define _Included_java_lang_RealToString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_RealToString
 * Method:    bigIntDigitGenerator
 * Signature: (JIZI)V
 */
JNIEXPORT void JNICALL Java_java_lang_RealToString_bigIntDigitGenerator
  (JNIEnv *, jobject, jlong, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
