/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_nio_ByteOrder */

#ifndef _Included_java_nio_ByteOrder
#define _Included_java_nio_ByteOrder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_nio_ByteOrder
 * Method:    isLittleEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_nio_ByteOrder_isLittleEndian
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
