/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_regex_Pattern */

#ifndef _Included_java_util_regex_Pattern
#define _Included_java_util_regex_Pattern
#ifdef __cplusplus
extern "C" {
#endif
#undef java_util_regex_Pattern_serialVersionUID
#define java_util_regex_Pattern_serialVersionUID 5073258162644648461LL
#undef java_util_regex_Pattern_UNIX_LINES
#define java_util_regex_Pattern_UNIX_LINES 1L
#undef java_util_regex_Pattern_CASE_INSENSITIVE
#define java_util_regex_Pattern_CASE_INSENSITIVE 2L
#undef java_util_regex_Pattern_COMMENTS
#define java_util_regex_Pattern_COMMENTS 4L
#undef java_util_regex_Pattern_MULTILINE
#define java_util_regex_Pattern_MULTILINE 8L
#undef java_util_regex_Pattern_LITERAL
#define java_util_regex_Pattern_LITERAL 16L
#undef java_util_regex_Pattern_DOTALL
#define java_util_regex_Pattern_DOTALL 32L
#undef java_util_regex_Pattern_UNICODE_CASE
#define java_util_regex_Pattern_UNICODE_CASE 64L
#undef java_util_regex_Pattern_CANON_EQ
#define java_util_regex_Pattern_CANON_EQ 128L
/*
 * Class:     java_util_regex_Pattern
 * Method:    closeImpl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_util_regex_Pattern_closeImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_util_regex_Pattern
 * Method:    compileImpl
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_java_util_regex_Pattern_compileImpl
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
