/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Math */

#ifndef _Included_java_lang_Math
#define _Included_java_lang_Math
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Math_E
#define java_lang_Math_E 2.718281828459045
#undef java_lang_Math_PI
#define java_lang_Math_PI 3.141592653589793
/*
 * Class:     java_lang_Math
 * Method:    acos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_acos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    asin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_asin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    atan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_atan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    atan2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_atan2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    cbrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_cbrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    ceil
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_ceil
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    cos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_cos
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    cosh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_cosh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    exp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_exp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    expm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_expm1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    floor
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_floor
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    hypot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_hypot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    IEEEremainder
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_IEEEremainder
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_log
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    log10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_log10
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    log1p
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_log1p
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    pow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_pow
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    rint
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_rint
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_sin
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    sinh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_sinh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_sqrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    tan
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_tan
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    tanh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_tanh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    nextafter
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Math_nextafter
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     java_lang_Math
 * Method:    nextafterf
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_java_lang_Math_nextafterf
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
