/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileDescriptor */

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_FileDescriptor
 * Method:    syncImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_syncImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
