/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddress */

#ifndef _Included_java_net_InetAddress
#define _Included_java_net_InetAddress
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_InetAddress_serialVersionUID
#define java_net_InetAddress_serialVersionUID 3286316764910316507LL
/*
 * Class:     java_net_InetAddress
 * Method:    byteArrayToIpString
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_byteArrayToIpString
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     java_net_InetAddress
 * Method:    ipStringToByteArray
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_net_InetAddress_ipStringToByteArray
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_net_InetAddress
 * Method:    gethostname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_gethostname
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    getaddrinfo
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddress_getaddrinfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_net_InetAddress
 * Method:    getnameinfo
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getnameinfo
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
