/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_Adler32 */

#ifndef _Included_java_util_zip_Adler32
#define _Included_java_util_zip_Adler32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_zip_Adler32
 * Method:    updateImpl
 * Signature: ([BIIJ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Adler32_updateImpl
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     java_util_zip_Adler32
 * Method:    updateByteImpl
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Adler32_updateByteImpl
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
