/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectOutputStream */

#ifndef _Included_java_io_ObjectOutputStream
#define _Included_java_io_ObjectOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef java_io_ObjectOutputStream_NOT_SC_BLOCK_DATA
#define java_io_ObjectOutputStream_NOT_SC_BLOCK_DATA -9L
/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldBool
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_ObjectOutputStream_getFieldBool
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldByte
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_java_io_ObjectOutputStream_getFieldByte
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldChar
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_java_io_ObjectOutputStream_getFieldChar
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldDouble
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_java_io_ObjectOutputStream_getFieldDouble
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldFloat
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_java_io_ObjectOutputStream_getFieldFloat
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldInt
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_java_io_ObjectOutputStream_getFieldInt
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldLong
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_java_io_ObjectOutputStream_getFieldLong
  (JNIEnv *, jclass, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldObj
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectOutputStream_getFieldObj
  (JNIEnv *, jclass, jobject, jclass, jstring, jstring);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    getFieldShort
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_java_io_ObjectOutputStream_getFieldShort
  (JNIEnv *, jclass, jobject, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
