/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcore_icu_TimeZones */

#ifndef _Included_libcore_icu_TimeZones
#define _Included_libcore_icu_TimeZones
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcore_icu_TimeZones
 * Method:    forCountryCode
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_libcore_icu_TimeZones_forCountryCode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     libcore_icu_TimeZones
 * Method:    getZoneStringsImpl
 * Signature: ([[Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_libcore_icu_TimeZones_getZoneStringsImpl
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     libcore_icu_TimeZones
 * Method:    getDisplayNameImpl
 * Signature: (Ljava/lang/String;ZILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcore_icu_TimeZones_getDisplayNameImpl
  (JNIEnv *, jclass, jstring, jboolean, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
