/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcore_io_IoUtils */

#ifndef _Included_libcore_io_IoUtils
#define _Included_libcore_io_IoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcore_io_IoUtils
 * Method:    close
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_libcore_io_IoUtils_close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libcore_io_IoUtils
 * Method:    getFd
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_libcore_io_IoUtils_getFd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libcore_io_IoUtils
 * Method:    pipe
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_libcore_io_IoUtils_pipe
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     libcore_io_IoUtils
 * Method:    setFd
 * Signature: (Ljava/io/FileDescriptor;I)V
 */
JNIEXPORT void JNICALL Java_libcore_io_IoUtils_setFd
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     libcore_io_IoUtils
 * Method:    setBlocking
 * Signature: (Ljava/io/FileDescriptor;Z)V
 */
JNIEXPORT void JNICALL Java_libcore_io_IoUtils_setBlocking
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
