/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcore_icu_NativeNormalizer */

#ifndef _Included_libcore_icu_NativeNormalizer
#define _Included_libcore_icu_NativeNormalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcore_icu_NativeNormalizer
 * Method:    normalizeImpl
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcore_icu_NativeNormalizer_normalizeImpl
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     libcore_icu_NativeNormalizer
 * Method:    isNormalizedImpl
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_libcore_icu_NativeNormalizer_isNormalizedImpl
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
