/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcore_icu_NativeIDN */

#ifndef _Included_libcore_icu_NativeIDN
#define _Included_libcore_icu_NativeIDN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcore_icu_NativeIDN
 * Method:    convertImpl
 * Signature: (Ljava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcore_icu_NativeIDN_convertImpl
  (JNIEnv *, jclass, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
