/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_harmony_luni_platform_OSFileSystem */

#ifndef _Included_org_apache_harmony_luni_platform_OSFileSystem
#define _Included_org_apache_harmony_luni_platform_OSFileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    lockImpl
 * Signature: (IJJIZ)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_lockImpl
  (JNIEnv *, jobject, jint, jlong, jlong, jint, jboolean);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    getAllocGranularity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_getAllocGranularity
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    length
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_length
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    unlockImpl
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_unlockImpl
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    fsync
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_fsync
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    seek
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_seek
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    readDirect
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_readDirect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    writeDirect
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_writeDirect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    read
 * Signature: (I[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    write
 * Signature: (I[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    readv
 * Signature: (I[I[I[II)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_readv
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    writev
 * Signature: (I[I[I[II)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_writev
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    truncate
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_truncate
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    transfer
 * Signature: (ILjava/io/FileDescriptor;JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_transfer
  (JNIEnv *, jobject, jint, jobject, jlong, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSFileSystem
 * Method:    ioctlAvailable
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSFileSystem_ioctlAvailable
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
