/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_harmony_luni_platform_OSMemory */

#ifndef _Included_org_apache_harmony_luni_platform_OSMemory
#define _Included_org_apache_harmony_luni_platform_OSMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    malloc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSMemory_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    memset
 * Signature: (IBJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_memset
  (JNIEnv *, jclass, jint, jbyte, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    memmove
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_memmove
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getByteArray
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getByteArray
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setByteArray
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setByteArray
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setShortArray
 * Signature: (I[SIIZ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setShortArray
  (JNIEnv *, jclass, jint, jshortArray, jint, jint, jboolean);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setIntArray
 * Signature: (I[IIIZ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setIntArray
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jboolean);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setFloatArray
 * Signature: (I[FIIZ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setFloatArray
  (JNIEnv *, jclass, jint, jfloatArray, jint, jint, jboolean);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getByte
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setByte
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getShort
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setShort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setShort
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getLong
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setLong
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setLong
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getFloat
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setFloat
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getDouble
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setDouble
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setDouble
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    getAddress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSMemory_getAddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    setAddress
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_setAddress
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    mmapImpl
 * Signature: (IJJI)I
 */
JNIEXPORT jint JNICALL Java_org_apache_harmony_luni_platform_OSMemory_mmapImpl
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    unmap
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_unmap
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    load
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_load
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    isLoaded
 * Signature: (IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_harmony_luni_platform_OSMemory_isLoaded
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_apache_harmony_luni_platform_OSMemory
 * Method:    flush
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_harmony_luni_platform_OSMemory_flush
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
