/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_harmony_luni_util_FloatingPointParser */

#ifndef _Included_org_apache_harmony_luni_util_FloatingPointParser
#define _Included_org_apache_harmony_luni_util_FloatingPointParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_harmony_luni_util_FloatingPointParser
 * Method:    parseDblImpl
 * Signature: (Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_org_apache_harmony_luni_util_FloatingPointParser_parseDblImpl
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_apache_harmony_luni_util_FloatingPointParser
 * Method:    parseFltImpl
 * Signature: (Ljava/lang/String;I)F
 */
JNIEXPORT jfloat JNICALL Java_org_apache_harmony_luni_util_FloatingPointParser_parseFltImpl
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
